# Generated by Django 4.1.5 on 2023-01-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=50, unique=True, verbose_name="사용자 ID"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
